version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - "./mongo-data:/data/db"
    ports:
      - "127.0.0.1:27017:27017"
  
  go:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - "./src:/dtalkGO"
    #restart: unless-stopped